# directory to hold all lineage folders and files
output_dir: desired_output_directory

# lineages to evaluate
lineages: example [P.1, B.1.1.318, R.1]

# number of background Gisaid sequences to include in the tree
subset_number: 300

# path to Gisaid files
gisaid_dir: /NetDrive/Projects/COVID-19/Other/master_gisaid/

# path to PHO master files
master_dir: /NetDrive/Projects/COVID-19/Other/master_fasta/

# path to reference genome
reference_genome: path_to_reference.gb

# path to the qc file used to filter the samples based on login date
# NOTE: this value is optional. if not specified, then the workflow will terminate with generating the trees (no annotation)
qc_list:




